x1 = float(input("Введите x1: "))
y1 = float(input("Введите y1: "))
x2 = float(input("Введите x2: "))
y2 = float(input("Введите y2: "))
a = abs(x2 - x1)
b = abs(y2 - y1)
P = 2 * (a + b)
S = a * b
print(P)
print(S)